// This file was generated by Slater.app - vetvision-main.js 

// Split text into words
let typeSplit = new SplitType('[animate]', {
  types: 'words',
  tagName: 'span'
});

// Initial fade-in animation for elements with [animate] attribute
let tl = gsap.timeline();
tl.from('[animate] .word', {
    opacity: 0,
    duration: 1,
    ease: 'power1.out',
    stagger: 0.1
  })
  .to('[animate] .word', {
    backgroundImage: 'linear-gradient(41.89deg, #ff007b 7.89%, #9339f3 97.13%)',
    duration: 1,
    ease: 'power1.inOut',
    stagger: 0.1
  }, 0.1)
  .to('[animate] .word', {
    backgroundImage: 'var(--gradient)',
    duration: 1,
    ease: 'power1.out',
    stagger: 0.1
  }, "-=0.5");

// Split text into words for all animate-section elements
let typeSplit2 = new SplitType('[animate-section]', {
  types: 'words',
  tagName: 'span'
});

// IntersectionObserver to trigger animations on entering the viewport
let observer = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    let element = entry.target;
    if (entry.isIntersecting) {
      // Animate when entering viewport
      let tl = gsap.timeline({
        onComplete: () => observer.unobserve(element) // Unobserve after animation completes
      });

      tl.fromTo(element.querySelectorAll('.word'), 
        { opacity: 0 }, // Start from opacity 0
        { 
          opacity: 1,
          backgroundImage: 'linear-gradient(41.89deg, #ff007b 7.89%, #9339f3 97.13%)',
          duration: 1,
          ease: 'power1.inOut',
          stagger: 0.2 
        })
        .to(element.querySelectorAll('.word'), {
          backgroundImage: 'var(--gradient)',
          duration: 1,
          ease: 'power1.inOut',
          stagger: 0.2
        });
    } else {
      // Reset animation when exiting viewport
      gsap.set(element.querySelectorAll('.word'), { opacity: 0 }); // Reset opacity to 0 on exit
      observer.observe(element); // Re-observe for future entry
    }
  });
}, { threshold: 0.5 });

// Apply the observer to each animate-section element
document.querySelectorAll('[animate-section]').forEach(element => {
  observer.observe(element);
});
