// This file was generated by Slater.app - vetvision-main.js 

// Split text into words
let typeSplit = new SplitType('[animate]', {
  types: 'words',
  tagName: 'span'
});

let tl = gsap.timeline();

// Initial fade-in
tl.from('[animate] .word', {
    opacity: 0,
    duration: 1,
    ease: 'power1.out',
    stagger: 0.1
  })
  // Animate to white gradient
  .to('[animate] .word', {
    backgroundImage: 'linear-gradient(41.89deg, #ff007b 7.89%, #9339f3 97.13%)',
    duration: 1,
    ease: 'power1.inOut',
    stagger: 0.1
  }, 0.1)
  // Animate back to original gradient
  .to('[animate] .word', {
    backgroundImage: 'var(--gradient)',
    duration: 1,
    ease: 'power1.out',
    stagger: 0.1
  }, "-=0.5");

// Split text into words for all animate-section elements
let typeSplit2 = new SplitType('[animate-section]', {
  types: 'words',
  tagName: 'span'
});

// Create animations for each element with animate-section attribute
document.querySelectorAll('[animate-section]').forEach(element => {
  let tl = gsap.timeline();
  
  tl.from(element.querySelectorAll('.word'), {
      opacity: 0.3,
      duration: 1,
      ease: 'power1.out',
      stagger: 0.2
    })
    .to(element.querySelectorAll('.word'), {
      backgroundImage: 'linear-gradient(41.89deg, #ff007b 7.89%, #9339f3 97.13%)',
      duration: 1,
      ease: 'power1.inOut',
      stagger: 0.2
    })
    .to(element.querySelectorAll('.word'), {
      backgroundImage: 'var(--gradient)',
      duration: 1,
      ease: 'power1.inOut',
      stagger: 0.2
    });
});
